export const NavItem = [
  { id: "home", title: "Home", url: "/" },
  { id: "blog", title: "Blog", url: "/blogs" },
  { id: "categories", title: "Categories", url: "/categories" },
  { id: "about", title: "About", url: "/about-us" },
  { id: "contact", title: "Contact", url: "/contact" },
];

export const FooterNavPageLinks = [
  { id: "about-us", title: "About us", link: "/about-us" },
  { id: "contact", title: "Contact us", link: "/contact" },
  { id: "sitemap", title: "Sitemap", link: "/sitemap" },
  { id: "privacyPolicy", title: "Privacy policy", link: "/privacyPolicy" },
  { id: "tos", title: "Terms of Service", link: "/tos" },
];

export const DummyBlogPost = [
  {
    id: 1,
    categories: ["Technology", "Health", "Business & Industrial"],
    title: "The Future of Artificial Intelligence",
    description: "Exploring the latest advancements in AI and its potential impact on industries.",
    image: "https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    trending: true,
  },
  {
    id: 2,
    categories: ["Food & Drink", "Lifestyle", "Travel"],
    title: "Top 10 Must-Try Restaurants in Paris",
    description: "Discover the culinary delights of Paris with our restaurant recommendations.",
    image: "https://images.pexels.com/photos/2085831/pexels-photo-2085831.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    trending: false,
  },
  {
    i: "as",
    id: 3,
    categories: ["Finance", "Technology"],
    title: "Investing in Cryptocurrencies: A Comprehensive Guide",
    description: "Learn the ins and outs of cryptocurrency investments and strategies.",
    image: "https://images.pexels.com/photos/6153354/pexels-photo-6153354.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    trending: true,
  },
  {
    id: 4,
    categories: ["Health", "Fitness", "Lifestyle"],
    title: "Mental Health Matters: Strategies for a Balanced Life",
    description: "Explore techniques for maintaining mental well-being and life balance.",
    image: "https://images.pexels.com/photos/2085831/pexels-photo-2085831.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    trending: false,
  },
  {
    id: 5,
    categories: ["Travel", "Hobbies & Leisure", "Sports"],
    title: "Adventure Sports in New Zealand: An Epic Journey",
    description: "Embark on a thrilling adventure with our guide to sports in New Zealand.",
    image: "https://images.pexels.com/photos/2085831/pexels-photo-2085831.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    trending: false,
  },
  {
    id: 6,
    categories: ["Technology", "Health", "Business & Industrial"],
    title: "The Future of Artificial Intelligence",
    description: "Exploring the latest advancements in AI and its potential impact on industries.",
    image: "https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    trending: true,
  },
  {
    id: 7,
    categories: ["Food & Drink", "Lifestyle", "Travel"],
    title: "Top 10 Must-Try Restaurants in Paris",
    description: "Discover the culinary delights of Paris with our restaurant recommendations.",
    image: "https://images.pexels.com/photos/2085831/pexels-photo-2085831.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    trending: false,
  },
  {
    id: 8,
    categories: ["Finance", "Technology"],
    title: "Investing in Cryptocurrencies: A Comprehensive Guide",
    description: "Learn the ins and outs of cryptocurrency investments and strategies.",
    image: "https://images.pexels.com/photos/2085831/pexels-photo-2085831.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    trending: true,
  },
  {
    id: 9,
    categories: ["Health", "Fitness", "Lifestyle"],
    title: "Mental Health Matters: Strategies for a Balanced Life",
    description: "Explore techniques for maintaining mental well-being and life balance.",
    image: "https://images.pexels.com/photos/2085831/pexels-photo-2085831.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    trending: false,
  },
  {
    id: 10,
    categories: ["Travel", "Hobbies & Leisure", "Sports"],
    title: "Adventure Sports in New Zealand: An Epic Journey",
    description: "Embark on a thrilling adventure with our guide to sports in New Zealand.",
    image: "https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    trending: false,
  },
];
